### PR TITLE
Prevent segfault on rare noisy occasions

### PR DESCRIPTION
**Pull request by jean-emmanuel**
#12 rebased on master :)

### CODE REVIEW

**Comment by x42** [comment]
Maybe there should also be some noise-floor filter. It seems wrong that the 3 bins can be sufficiently close to 1e-9 and result in a div by zero or that interpolation becomes negative to cancel out `j` which is at least `_ifmin = sample-rate /1200`

I'm curious, can you

```
if (_cycle < 0) {
 printf ("crash ahead: x=%e y=%e z=%e\n", x, y, z);
}
```

I guess the actual segfault happens later at
```
dr = _cycle * (int)(ceilf (_frsize / _cycle));
```

**Comment by jean-emmanuel** [comment]
Le 10/11/2019 à 20:04, Robin Gareus a écrit :
>
> Maybe there should also be some noise-floor filter. It seems wrong 
> that the 3 bins can be sufficiently close to 1e-9 and result in a div 
> by zero or that interpolation becomes negative to cancel out |j| which 
> is at least |_ifmin = sample-rate /1200|
>
> I'm curious, can you
>
> |if (_cycle < 0) { printf ("crash ahead: x=%e y=%e z=%e\n", x, y, z); }|

Here:

crash ahead: x=9.963503e-01 y=9.963504e-01 z=9.963504e-01 _cycle=-inf j=168


> ||
>
> I guess the actual segfault happens later at
>
> |dr = _cycle * (int)(ceilf (_frsize / _cycle));|


indeed !

**Comment by x42** [comment]
OK, So it seems this `<= 0` check is the most practical fix after all.

**Comment by x42** [comment]
rebased  & merged as 5a44436e7. Thanks!

**Comment by jean-emmanuel** [comment]
Thank you !

**Comment by jean-emmanuel** [comment]
Ahem... two other cases :
```
crash ahead: x=9.988863e-01 y=9.988863e-01 z=9.988863e-01 _cycle=-nan
crash ahead: x=9.999988e-01 y=9.999988e-01 z=9.999987e-01 _cycle=inf
```
I had to blow on my microphone for some time but you never know when it happens in live ! Maybe it's better to switch x, y and z to doubles after all, no ?

**Comment by x42** [comment]
doubles won't help, just make it less likely. We probably need to add explicit checks

**Comment by x42** [comment]
How about 
```
if  ((z - 2 * y + x) >  2e-9f) {
  _cycle = j + 0.5f * (x - z) / (z - 2 * y + x - 1e-9f);
}
```

the 1e-9 is to prevent denormals.

**Pull request closed without merging**
